name: Hello World

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello World!"
      - name: Print date
        run: date
      - name: Print directory content
        run: ls -l
